---
title: "Intro to Data"
author: "Mike Silva"
date: "August 24, 2018"
output: html_document
---

## 1.8 Smoking habits of UK residents

A survey was conducted to study the smoking habits of UK residents. Below is a data matrix displaying a portion of the data collected in this survey. Note that “£” stands for British Pounds Sterling, “cig” stands for cigarettes, and “N/A” refers to a missing component of the data.

|   |   sex  | age | marital | grossIncome | smoke | amtWeekends | amtWeekdays |
|---| -----: | --: | -------:| -----------: | ----: | ----------: | ----------: |
| 1 | Female | 42  | Single  | Under £2,600 | Yes | 12 cig/day | 12 cig/day | 
| 2 | Male	 | 44	 | Single  | £10,400 to £15,600 | No | N/A | N/A | 
| 3 | Male 	 | 53  | Married | Above £36,400 | Yes | 6 cig/day | 6 cig/day |
| ... | ... | ... | ... | ... | ...| ... | ... |
| 1691 | Male | 40 | Single | £2,600 to £5,200 | Yes | 8 cig/day | 8 cig/day |

(a) What does each row of the data matrix represent?

**A survey response**

(b) How many participants were included in the survey?

**1,691**

(c) Indicate whether each variable in the study is numerical or categorical. If numerical, identify as continuous or discrete. If categorical, indicate if the variable is ordinal.

* __sex - non-ordinal categorical__
* __age - discrete numerical__
* __marital - non-ordinal categorical__
* __grossIncome - ordinal categorical__
* __smoke - non-ordinal categorical__
* __amtWeekends - ordinal categorical__
* __amtWeekdays - ordinal categorical__

## 1.10 Cheaters, scope of inference

Exercise 1.5 introduces a study where researchers studying the relationship between honesty, age, and self-control conducted an experiment on 160 children between the ages of 5 and 15. The researchers asked each child to toss a fair coin in private and to record the outcome (white or black) on a paper sheet, and said they would only reward children who report white. Half the students were explicitly told not to cheat and the others were not given any explicit instructions. Differences were observed in the cheating rates in the instruction and no instruction groups, as well as some differences across children’s characteristics within each group.

(a) Identify the population of interest and the sample in this study.

**Population of interest: The general population**
**Study sample: Children ages 5 to 15**

(b) Comment on whether or not the results of the study can be generalized to the population, and if the findings of the study can be used to establish causal relationships.

**The results cannot be generalized to the population.  The findings can not be used to estalish a causal relationship**

## 1.28 Reading the paper

Below are excerpts from two articles published in the NY Times:

(a) An article titled Risks: Smokers Found More Prone to Dementia states the following: 

“Researchers analyzed data from 23,123 health plan members who participated in a voluntary exam and health behavior survey from 1978 to 1985, when they were 50-60 years old. 23 years later, about 25% of the group had dementia, including 1,136 with Alzheimer’s disease and 416 with vascular dementia. After adjusting for other factors, the researchers concluded that pack-a-day smokers were 37% more likely than nonsmokers to develop dementia, and the risks went up with increased smoking; 44% for one to two packs a day; and twice the risk for more than two packs.”

Based on this study, can we conclude that smoking causes dementia later in life? Explain your reasoning.

**No.  Smoking and dementia are correlated in the study, but correlation is not causation**

(b) Another article titled The School Bully Is Sleepy states the following:

“The University of Michigan study, collected survey data from parents on each child’s sleep habits and asked both parents and teachers to assess behavioral concerns. About a third of the students studied were identified by parents or teachers as having problems with disruptive behavior or bullying. The researchers found that children who had behavioral issues and those who were identified as bullies were twice as likely to have shown symptoms of sleep disorders.”

A friend of yours who read the article says, “The study shows that sleep disorders lead to bullying in school children.” Is this statement justified? If not, how best can you describe the conclusion that can be drawn from this study?

**No the statement is not justified. You can conclude that the two are correlated but there may be other causal factors that haven't been articulated by the article.**

## 1.36 Exercise and mental health

A researcher is interested in the effects of exercise on mental health and he proposes the following study: Use stratified random sampling to ensure representative proportions of 18-30, 31-40 and 41-55 year olds from the population. Next, randomly assign half the subjects from each age group to exercise twice a week, and instruct the rest not to exercise. Conduct a mental health exam at the beginning and at the end of the study, and compare the results.

(a) What type of study is this?

**This is a randomized experiment.**

(b) What are the treatment and control groups in this study?

**The treatment group are those who exercise and the control group do not exercise.**

(c) Does this study make use of blocking? If so, what is the blocking variable?

**No it does not.**

(d) Does this study make use of blinding?

**No it does not as the researcher instructs the participant to exercise or not.**

(e) Comment on whether or not the results of the study can be used to establish a causal relationship between exercise and mental health, and indicate whether or not the conclusions can be generalized to the population at large.

**Results from this study may establish a causal relationship between exercise and mental health holding all other variables constant.  The conclusions could be generalize if the sample size is large enough.**

(f) Suppose you are given the task of determining if this proposed study should get funding.  Would you have any reservations about the study proposal?

**I would be concerned about all the other variables that affect mental health besides the amount of exercise.**

## 1.48  Stats scores

Below are the final exam scores of twenty introductory statistics students.
57, 66, 69, 71, 72, 73, 74, 77, 78, 78, 79, 79, 81, 81, 82, 83, 83, 88, 89, 94

Create a box plot of the distribution of these scores. The five number summary provided below may be useful.

| Min |  Q1  | Q2 (Median) |  Q3  | Max |
| --: | ---: | ----------: | ---: | --: |
| 57  | 72.5 |     78.5    | 82.5 | 94  |

```{r 1.48}
scores <- c(57, 66, 69, 71, 72, 73, 74, 77, 78, 78, 79, 79, 81, 81, 82, 83, 83, 88, 89, 94)
boxplot(scores)
```

## 1.50 Mix-and-match

Describe the distribution in the histograms below and match them to the box plots.

## 1.56 Distributions and appropriate statistics, Part II

For each of the following, state whether you expect the distribution to be symmetric, right skewed, or left skewed. Also specify whether the mean or median would best represent a typical observation in the data, and whether the variability of observations would be best represented using the standard deviation or IQR. Explain your reasoning. 

(a) Housing prices in a country where 25% of the houses cost below $350,000, 50% of the houses cost below $450,000, 75% of the houses cost below $1,000,000 and there are a meaningful number of houses that cost more than $6,000,000.

(b) Housing prices in a country where 25% of the houses cost below $300,000, 50% of the houses cost below $600,000, 75% of the houses cost below $900,000 and very few houses that cost more than $1,200,000.

(c) Number of alcoholic drinks consumed by college students in a given week. Assume that most of these students don’t drink since they are under 21 years old, and only a few drink excessively.

(d) Annual salaries of the employees at a Fortune 500 company where only a few high level executives earn much higher salaries than all the other employees.

## 1.70 Heart transplants

The Stanford University Heart Transplant Study was conducted to determine whether an experimental heart transplant program increased lifespan. Each patient entering the program was designated an experimental heart transplant candidate, meaning that he was gravely ill and would most likely benefit from a new heart. Some patients got a transplant and some did not. The variable transplant indicates which group the patients were in; patients in the treatment group got a transplant and those in the control group did not. Another variable called survived was used to indicate whether or not the patient was alive at the end of the study. Of the 34 patients in the control group, 30 died. Of the 69 people in the treatment group, 45 died.

(a) Based on the mosaic plot, is survival independent of whether or not the patient got a transplant? Explain your reasoning.

(b) What do the box plots below suggest about the efficaacy (effectiveness) of the heart transplant treatment.

(c) What proportion of patients in the treatment group and what proportion of patients in the control group died?

(d) One approach for investigating whether or not the treatment is e↵ective is to use a randomization technique.

i. What are the claims being tested?

ii. The paragraph below describes the set up for such approach, if we were to do it withut using statistical software. Fill in the blanks with a number or phrase, whichever is appropriate.

We write alive on cards representing patients who were alive at the end of the study, and dead on cards representing patients who were not. Then, we shuffle these cards and split them into two groups: one group of size representing treatment, and another group of size representing control. We calculate the difference between the proportion of dead cards in the treatment and control groups (treatment - control) and record this value. We repeat this 100 times to build a distribution centered at . Lastly, we calculate the fraction of simulations where the simulated differences in proportions are . If this fraction is low, we conclude that it is unlikely to have observed such an outcome by chance and that the null hypothesis should be rejected in favor of the alternative.

iii. What do the simulation results shown below suggest about the effectiveness of the transplant program?