---
title: "Probability"
author: "Mike Silva"
date: "September 9, 2018"
output: html_document
---
## Description

The following is the graded problems for the Probability chapter of Open Intro to Statistics.  My answers to the questions are **bolded.**  The headers correspond to a question.

## 2.6 Dice rolls

If you roll a pair of fair dice, what is the probability of

(a) getting a sum of 1? **0.  It is impossible.**

(b) getting a sum of 5? **4/36 or 0.1111111**

(c) getting a sum of 12? **1/36 or 0.02777778**

## 2.8 Poverty and language

The American Community Survey is an ongoing survey that provides data every year to give communities the current information they need to plan investments and services. The 2010 American Community Survey estimates that 14.6% of Americans live below the poverty line, 20.7% speak a language other than English (foreign language) at home, and 4.2% fall into both categories.

(a) Are living below the poverty line and speaking a foreign language at home disjoint? **No because if they were there wouldn't be the 4.2% that fall into both categories.  It would be 0%.**

(b) Draw a Venn diagram summarizing the variables and their associated probabilities.
```{r venn_diagram, warning=FALSE, message=FALSE, results='hide'}
library(VennDiagram)
grid.newpage()
draw.pairwise.venn(area1 = 20.7, area2 = 14.6, cross.area = 4.2, category = c("Foreign Lang", "Poverty"), fill = c("cornflower blue", "yellow"))
```


(c) What percent of Americans live below the poverty line and only speak English at home? **10.4%**

(d) What percent of Americans live below the poverty line or speak a foreign language at home? **26.9%**

(e) What percent of Americans live above the poverty line and only speak English at home? **73.1%**

(f) Is the event that someone lives below the poverty line independent of the event that the person speaks a foreign language at home?  **No.  If they were independent than the probability of living in poverty would be the same for those that speak english and those that don't.**

## 2.20 Assortative mating

Assortative mating is a nonrandom mating pattern where individuals with similar genotypes and/or phenotypes mate with one another more frequently than what would be expected under a random mating pattern. Researchers studying this topic collected data on eye colors of 204 Scandinavian men and their female partners. The table below summarizes the results. For simplicity, we only include heterosexual relationships in this exercise.

<table class="table table-condensed">
<thead>
<tr class="header"><th colspan="2"></th><th colspan="3"><i>Partner (female)</i></th><th></th></tr>
</thead>
<tbody>
<tr><th colspan="2"></th><th>Blue</th><th>Brown</th><th>Green</th><th>Total</th></tr>
<tr><th rowspan="3"><i>Self (male)</i></th><th>Blue</th><td>78</td><td>23</td><td>13</td><td>114</td></tr>
<tr><th>Brown</th><td>19</td><td>23</td><td>12</td><td>54</td></tr>
<tr><th>Green</th><td>11</td><td>9</td><td>16</td><td>36</td></tr>
<tr><th></th><th>Total</th><td>108</td><td>55</td><td>41</td><td>204</td></tr>
</tbody>
</table>

(a) What is the probability that a randomly chosen male respondent or his partner has blue eyes? **(108 + 114 - 78)/204 = 144/204 = 0.7058824**

(b) What is the probability that a randomly chosen male respondent with blue eyes has a partner with blue eyes? **78/114 = 0.6842105**

(c) What is the probability that a randomly chosen male respondent with brown eyes has a partner with blue eyes?  **19/54 = 0.3518519**

What about the probability of a randomly chosen male respondent with green eyes having a partner with blue eyes? **11/36 = 0.3055556**

(d) Does it appear that the eye colors of male respondents and their partners are independent? Explain your reasoning.  **No.  If they were independent, than the female eye colors would be evenly distributed across the categories.**

## 2.30 Books on a bookshelf

The table below shows the distribution of books on a bookcase based on whether they are nonfiction or fiction and hardcover or paperback.

<table class="table table-condensed">
<thead>
<tr class="header"><th colspan="2"></th><th colspan="3"><i>Format</i></th></tr>
</thead>
<tbody>
<tr><th colspan="2"></th><th>Hardcover</th><th>Paperback</th><th>Total</th></tr>
<tr><th rowspan="2"><i>Type</i></th><th>Fiction</th><td>13</td><td>59</td><td>72</td></tr>
<tr><th>Nonfiction</th><td>15</td><td>8</td><td>23</td></tr>
<tr><td></td><th>Total</th><td>28</td><td>67</td><td>95</td></tr>
</tbody>
</table>

(a) Find the probability of drawing a hardcover book first then a paperback fiction book second when drawing without replacement.

(b) Determine the probability of drawing a fiction book first and then a hardcover book second, when drawing without replacement.

(c) Calculate the probability of the scenario in part (b), except this time complete the calculations under the scenario where the first book is placed back on the bookcase before randomly drawing the second book.

(d) The final answers to parts (b) and (c) are very similar. Explain why this is the case.

## 2.38 Baggage fees

An airline charges the following baggage fees: $25 for the first bag and $35 for the second. Suppose 54% of passengers have no checked luggage, 34% have one piece of checked luggage and 12% have two pieces. We suppose a negligible portion of people check more than two bags.

(a) Build a probability model, compute the average revenue per passenger, and compute the corresponding standard deviation.

(b) About how much revenue should the airline expect for a flight of 120 passengers? With what standard deviation? Note any assumptions you make and if you think they are justified.

## 2.44 Income and gender

The relative frequency table below displays the distribution of annual total personal income (in 2009 inflation-adjusted dollars) for a representative sample of 96,420,486 Americans. These data come from the American Community Survey for 2005-2009. This sample is comprised of 59% males and 41% females.

|         Income       | Total |
|----------------------|-------|
| $1 to $9,999 or loss | 2.2%  |
| $10,000 to $14,999   | 4.7%  |
| $15,000 to $24,999   | 15.8% |
| $25,000 to $34,999   | 18.3% |
| $35,000 to $49,999   | 21.2% |
| $50,000 to $64,999   | 13.9% |
| $65,000 to $74,999   | 5.8%  |
| $75,000 to $99,999   | 8.4%  |
| $100,000 or more     | 9.7%  |

(a) Describe the distribution of total personal income.

(b) What is the probability that a randomly chosen US resident makes less than $50,000 per year?

(c) What is the probability that a randomly chosen US resident makes less than $50,000 per year and is female? Note any assumptions you make.

(d) The same data source indicates that 71.8% of females make less than $50,000 per year. Use this value to determine whether or not the assumption you made in
part (c) is valid.