---
title: "DATA 605 Week 15"
author: "Mike Silva"
date: "May 6, 2019"
output: html_document
---

## Question 1

Find the equation of the regression line for the given points. Round any final values to the nearest hundredth, if necessary.

( 5.6, 8.8 ), ( 6.3, 12.4 ), ( 7, 14.8 ), ( 7.7, 18.2 ), ( 8.4, 20.8 )

## Question 2

Find all local maxima, local minima, and saddle points for the function given below. Write your answer(s) in the form ( x, y, z ). Separate multiple points with a comma.

$$f(x,y)=24x-6xy^2-8y^3$$

## Question 3

A grocery store sells two brands of a product, the "house" brand and a "name" brand. The manager estimates that if she sells the "house" brand for x dollars and the "name" brand for y dollars, she will be able to sell 81  21x + 17y units of the "house" brand and 40 + 11x  23y units of the "name" brand.

**Step 1.** Find the revenue function R ( x, y ).

**Step 2.** What is the revenue if she sells the "house" brand for $2.30 and the "name" brand for $4.10?

## Question 4

A company has a plant in Los Angeles and a plant in Denver. The firm is committed to produce a total of 96 units of a product each week. The total weekly cost is given by $C(x,y)=\frac{1}{6}x^2+\frac{1}{6}y^2+7x+25y+700$, where x is the number of units produced in Los Angeles and y is the number of units produced in Denver. How many units should be produced in each plant to minimize the total weekly cost?

## Question 5

Evaluate the double integral on the given region.

$\int{\int{(e^{8x+3y})dA}}$; $R: 2 \leq x \leq 4$ and $2 \leq y \leq 4$

Write your answer in exact form without decimals.
