---
title: "DATA 605 Week 13"
author: "Mike Silva"
date: "April 23, 2019"
output: 
  rmdformats::readthedown:
    highlight: kate
---

## Question 1
**Use integration by substitution to solve the integral below.**

$$ \int{4e^{-7x}dx}$$

The integral of a constant times a function is the constant times the integral of the function so

$$ \int{4e^{-7x}dx} \rightarrow 4 \int{e^{-7x}dx}$$

Let u = -7x

$$ du = -7dx \rightarrow \frac{du}{-7}=dx\rightarrow dx = -\frac{1}{7}du$$

Substituded in

$$ 4 \int{e^{-7x}dx} \rightarrow 4\int{-\frac{e^u}{7}du} \rightarrow -\frac{4}{7}\int{e^u du}$$

Since  $\int{e^u du} = e^u$ we get

$$ -\frac{4}{7}\int{e^u du} \rightarrow -\frac{4}{7}e^u$$

Substitute for u we get

$$ -\frac{4}{7}e^{-7x} + C$$

## Question 2

**Biologists are treating a pond contaminated with bacteria. The level of contamination is changing at a rate of $\frac{dN}{dt}=-\frac{3150}{t^4}-220$ bacteria per cubic centimeter per day, where t is the number of days since treatment began. Find a function N(t) to estimate the level of contamination if the level after 1 day was 6530 bacteria per cubic centimeter.**

## Question 3

**Find the total area of the red rectangles in the figure below, where the equation of the line is f(x) = 2x-9.**

## Question 4

**Find the area of the region bounded by the graphs of the given equations **

$$y=x^2-2x-2, y=x+2$$

## Question 5

**A beauty supply store expects to sell 110 flat irons during the next year. It costs $3.75 to store one flat iron for one year. There is a fixed cost of $8.25 for each order. Find the lot size and the number of orders per year that will minimize inventory costs.**

## Question 6

**Use integration by parts to solve the integral below.**

$$\int{ln(9x) \times x^6 dx}$$


## Question 7

**Determine whether f(x) is a probability density function on the interval $[1, e^6]$ . If not, determine the value of the definite integral.**

$$f(x)=\frac{1}{6x}$$

